on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 18 * * *'

name: CI

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - linux-stable
          - linux-musl-stable
          - linux-beta
          - linux-nightly
          - macos-stable
          - windows-stable
        include:
          - build: linux-stable
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            rust: stable
          - build: linux-musl-stable
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            rust: stable
          - build: linux-beta
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            rust: beta
          - build: linux-nightly
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            rust: nightly
          - build: macos-stable
            os: macos-latest
            target: x86_64-apple-darwin
            rust: stable
          - build: windows-stable
            os: windows-latest
            target: x86_64-pc-windows-msvc
            rust: stable
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - run: cargo test --workspace --all-features --target ${{ matrix.target }}

  test-cross:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ netbsd ]
        include:
          - build: netbsd
            os: ubuntu-22.04
            target: x86_64-unknown-netbsd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Use Cross
        shell: bash
        run: |
          cargo install cross
          echo "CARGO=cross" >> $GITHUB_ENV
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV

      - name: Show command used for Cargo
        run: |
          echo "cargo command is: ${{ env.CARGO }}"
          echo "target flag is: ${{ env.TARGET_FLAGS }}"

      - name: cargo test
        run: ${{ env.CARGO }} test --verbose ${{ env.TARGET_FLAGS }}

  fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --workspace --all-features --tests -- -Dwarnings

  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          log-level: warn
          command: check
          arguments: --all-features
